all:
  children:
    quizbot:
      hosts:
        quizbot_server:
          ansible_host: "{{ server_ip | mandatory }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
      vars:
        app_user: ubuntu
        app_group: ubuntu
        app_dir: /opt/quizbot

        postgres_disk_device: /dev/vdb
        postgres_disk_mount: /data/postgres
        postgres_disk_fstype: ext4