apiVersion: v1
kind: Namespace
metadata:
  name: quizbot
---
# PVC для Postgres (диск)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: quizbot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Minikube сам создаст PV
  resources:
    requests:
      storage: 1Gi
---
# Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: quizbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_DB
          value: quizbot
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: quizbot-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quizbot-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# Quizbot (твоё приложение)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizbot
  namespace: quizbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizbot
  template:
    metadata:
      labels:
        app: quizbot
    spec:
      containers:
      - name: quizbot
        image: {{ docker_image }}:{{ docker_tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # 👇 Здесь K8s сам "распакует" .env в переменные окружения
        envFrom:
        - secretRef:
            name: quizbot-secrets
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10