heat_template_version: 2015-10-15

description: |
  Базовая инфраструктура для QuizBot

parameters: 
  image_id:
    type: string
    label: Image
    default: "ubuntu-24.04"
  
  flavor_id:
    type: string
    label: Flavor
    default: "m1.small"
  
  key_name:
    type: string
    label: SSH Key
    default: "shihalev-key-pair"
  
  existing_subnet_id:
    type: string
    label: Existing Subnet ID
    default: "6a69f855-8a2d-4994-baf0-ed4feedd897b"

resources:
  bot_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: shihalev-sg
      description: SG for QuizBot
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
          remote_ip_prefix: 0.0.0.0/0

  postgres_volume:
    type: OS::Cinder::Volume
    deletion_policy: Delete
    properties:
      name: postgres-vol
      size: 10
      description: PostgreSQL data volume

  bot_server:
    type: OS::Nova::Server
    properties:
      name: shihalev-bot-vm
      image: { get_param: image_id }
      flavor: { get_param: flavor_id }
      key_name: { get_param: key_name }
      networks:
        - subnet: { get_param: existing_subnet_id }
      security_groups:
        - { get_resource: bot_security_group }

  postgres_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: bot_server }
      volume_id: { get_resource: postgres_volume }
      mountpoint: /dev/vdb

outputs:
  server_private_ip:
    description: "Private IP address"
    value: { get_attr: [bot_server, first_address] }
  
  server_name:
    description: "Server name"
    value: { get_attr: [bot_server, name] }
  
  ssh_command:
    description: "SSH command (via bastion/VPN)"
    value: 
      str_replace:
        template: "ssh -i <key> ubuntu@{ip}"
        params: 
          ip: { get_attr: [bot_server, first_address] }
  
  console_url:
    description: "How to access console"
    value: "OpenStack Dashboard → Compute → Instances → shihalev-bot-vm → Console"